lensesio/stream-reactor

- README.md
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/CassandraSinkConnector.scala
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/CassandraSinkTask.scala
* Testing webhook
* Updating build status
* Updating build status based on Embeddable Plugin
* Update README.md
* Completing migration to Jenkins
* removed print props since it dumps the password
* merge into master (#27) (#28)
* Testing webhook
* Updating build status
* Updating build status based on Embeddable Plugin
* Update README.md
* Completing migration to Jenkins
* removed print props since it dumps the password
> mereging (#29)

- kafka-connect-voltdb/src/main/scala/com/datamountaineer/streamreactor/connect/voltdb/StructFieldsExtractor.scala
- kafka-connect-voltdb/src/main/scala/com/datamountaineer/streamreactor/connect/voltdb/writers/VoltConnectionConnectFn.scala
- kafka-connect-voltdb/src/main/scala/com/datamountaineer/streamreactor/connect/voltdb/writers/VoltDbMetadataReader.scala
> supporting decimal, date, time and timestamp from connect sinkrecord

- build.gradle
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/CassandraJsonWriter.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/TestConfig.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/TestCassandraJsonWriterFieldSelection.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraReaderIncr.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTask.scala
- kafka-connect-elastic/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/ElasticJsonWriter.scala
- kafka-connect-hazelcast/src/main/scala/com/datamountaineer/streamreactor/connect/hazelcast/sink/HazelCastWriter.scala
- kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/sink/writer/converters/JsonMessageConverter.scala
- kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisDbWriter.scala
which introduces the simple json converter handling decimals, date, time, timestamp and improves performance since is not going from json to array and back to json
> upgrading to common lib 0.4 

- kafka-connect-voltdb/src/main/scala/com/datamountaineer/streamreactor/connect/voltdb/StructFieldsExtractor.scala
can't ignore default/null values from struct the voltdb schema expects a number of parameters
raising an error if specific fields are selected but they are not present in the sinkrecord
> fixing field extractor

- kafka-connect-hbase/src/main/scala/com/datamountaineer/streamreactor/connect/hbase/BytesHelper.scala
- kafka-connect-hbase/src/main/scala/com/datamountaineer/streamreactor/connect/hbase/StructFieldsExtractorBytes.scala
handling the logical connect schema types
> throw an error if requested schema fields are not present

- kafka-connect-influxdb/build.gradle
- kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/StructFieldsExtractor.scala
- kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/config/InfluxSettings.scala
- kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/config/InfluxSinkConfig.scala
- kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/InfluxBatchPointsBuilderFn.scala
- kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/InfluxDbWriter.scala
- kafka-connect-influxdb/src/test/scala/com/datamountaineer/streamreactor/connect/influx/InfluxBatchPointsBuilderFnTest.scala
- kafka-connect-influxdb/src/test/scala/com/datamountaineer/streamreactor/connect/influx/StructFieldsExtractorTest.scala
- kafka-connect-rethink/src/test/scala/com/datamountaineer/streamreactor/connect/rethink/sink/TestReThinkSinkConverter.scala
adding support for schemaless sink record or a  record with string schema and json payload
> supportning non avro messages

- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoConfig.scala
- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoSinkSettings.scala
- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/MongoWriter.scala
- kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/SinkRecordToDocumentTest.scala
- kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoSinkSettingsTest.scala
- kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/MongoSinkConnectorTest.scala
- kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/MongoWriterTest.scala
simplify config. allow connection string to be specified in full mong…odb:// format. removed default connection value
> Configuration simplification

- kafka-connect-blockchain/src/main/scala/com/datamountaineer/streamreactor/connect/blockchain/data/Output.scala
A minor fix - but did not look right
> it's non optional in the case class ..

- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraConfig.scala
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraConfigConstants.scala
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraSettings.scala
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/CassandraJsonWriter.scala
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/CassandraSinkTask.scala
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/config/TestCassandraSinkConfig.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/config/TestCassandraSinkSettings.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/SinkRecordToJsonTest.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/TestCassandraSinkTask.scala
removed the timer to print the stats since it wasn't thread safe (stats are still printed on 60 seconds basis)
> added support to specify the consistency level

- build.gradle
- kafka-connect-hbase/src/main/scala/com/datamountaineer/streamreactor/connect/hbase/StructFieldsExtractorBytes.scala
- kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/StructFieldsExtractor.scala
- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/converters/SinkRecordConverter.scala
- kafka-connect-rethink/src/main/scala/com/datamountaineer/streamreactor/connect/rethink/sink/SinkRecordConversion.scala
the support for logical types was not perfect.  made all the changes required including to common lib
> fixing the support for logical types

- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/CassandraConnection.scala
currently we pass the entire string provided. using ',' to split the contact nodes
> fixing the cluster contact list

- build.gradle
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/TestConfig.scala
- kafka-connect-coap/src/main/scala/com/datamountaineer/streamreactor/connect/coap/configs/CoapSettings.scala
- kafka-connect-coap/src/main/scala/com/datamountaineer/streamreactor/connect/coap/connection/CoapManager.scala
- kafka-connect-coap/src/test/scala/com/datamountaineer/streamreactor/connect/coap/TestBase.scala
- kafka-connect-hbase/src/main/scala/com/datamountaineer/streamreactor/connect/hbase/StructFieldsExtractorBytes.scala
- kafka-connect-hbase/src/test/scala/com/datamountaineer/streamreactor/connect/hbase/StructFieldsExtractorTest.scala
- kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/StructFieldsExtractor.scala
fixing 'Schema not supported'
fixing NPE tests on 0.10.1 when timestamp is required on sinkrecord
> upgrading to common 0.6.7

- conf/jms-sink.properties
> JMS sink: fix sample configuration

- kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/domain/JMSStructMessage.scala
Make properties create a java list of Struct using property schema.
> Fix Properties

- README.md
- kafka-connect-elastic5/build.gradle
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/ElasticJsonWriter.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/ElasticWriter.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/config/ClientType.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/config/ElasticConfig.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/config/ElasticConfigConstants.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/config/ElasticSettings.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/indexname/CreateIndex.scala
- kafka-connect-elastic5/src/test/scala/com/datamountaineer/streamreactor/connect/elastic/TestElasticBase.scala
- kafka-connect-elastic5/src/test/scala/com/datamountaineer/streamreactor/connect/elastic/TestElasticWriter.scala
- kafka-connect-elastic5/src/test/scala/com/datamountaineer/streamreactor/connect/elastic/TestElasticWriterSelection.scala
> add support for http elastic4s client, the default is tcp

- build.gradle
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/utils/CassandraUtils.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/utils/TestSchemaConverter.scala
small perf improvement by caching the struct schema
> decimals are handled correctly now

- kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSSourceTaskTest.scala
Previously we were not checking for prematurely acked messages (meaning someone could change to Auto-Ack and the tests would pass).
> Fix: Improve JMS acking test

- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraSourceTask.scala
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CqlGenerator.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/TestCassandraConnectionSecure.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/TestConfig.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/TestCassandraJsonWriter.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskTimestamp.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskTimestampLong.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskTimeuuid.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskTimeuuidLong.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceUtil.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCqlGenerator.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestTableUtil.scala
Fixed two tests that were failing
- `TestCassandraSourceTaskTimeuuidLong`
- `TestCassandraSourceTaskTimestammpLong`
Also refactored some of the test utils to be more DRY
> Fix the Cassandra Source long running tests

- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
Testing the Cassandra Source (see #278 and #300) we were finding that data was getting "lost". We would insert 200,000 rows and only get 199,000 in the Kafka topic. 
We found that making sure that the connector did not query with an upperbound in the time range to close to present would eliminate this problem. We found 30 seconds to be a good delay.
the code is checked in with the delay value set to 0 so that the tests still run.
> Cassandra Source: added delay to the time slice upper bounds calculation

- build.gradle
- kafka-connect-influxdb/build.gradle
- kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/InfluxBatchPointsBuilder.scala
- kafka-connect-influxdb/src/test/scala/com/datamountaineer/streamreactor/connect/influx/InfluxBatchPointsBuilderTest.scala
allowing dynamic measures in influxdb (from payload fields)
allowing timestamp unit
allowing tag names aliasing
> using latest kcql and common lib

- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala
- kafka-connect-mqtt/src/test/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManagerTest.scala
Registering mqtt-source-connector with 'connection.clean=false' occasionally causes NullPointerException when MQTT broker holds messages.
```
(com.datamountaineer.streamreactor.connect.mqtt.source.MqttManager:74)
java.lang.NullPointerException
at com.datamountaineer.streamreactor.connect.mqtt.source.MqttManager.messageArrived(MqttManager.scala:63)
at org.eclipse.paho.client.mqttv3.internal.CommsCallbahk.deliverMessage(CommsCallback.java:475)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:379)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:183)
at java.lang.Thread.run(Thread.java:748)
```
MqttManager class instantiates MqttClient and sets callback before instantiates LinkedBlockingQueue.
However, callback …
> Fixing NullPointerException at MQTT source

- build.gradle
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/TestConfig.scala
- kafka-connect-influxdb/build.gradle
- kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/TestBase.scala
- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala
upgrading to kcql 2.4.0 and common 0.9.3
> mqtt source allows kafka message key definition

- kafka-connect-pulsar/build.gradle
> add pulsar-checksum-1.20.0-incubating jar to dependencies

- README.md
> reduce image size

- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/connection/MqttClientConnectionFn.scala
> Fix in MQTT connector when use user/password auth

- build.gradle
should be avoided - unless u want to use local cache
> comment out mavenLocal

- kafka-connect-elastic/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/config/ElasticConfigConstants.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/ElasticSinkTask.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/config/ElasticConfig.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/config/ElasticConfigConstants.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/ElasticSinkTask.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticConfig.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticConfigConstants.scala
- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoConfig.scala
- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoConfigConstants.scala
- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoSettings.scala
- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/MongoWriter.scala
- kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoSettingsTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/387)
> move batch size to kcql and add retry interval to elastic5 and elastic6

- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/KuduConverter.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/390)
> handling the logical types

- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTypeConverter.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/394)
> Fix bigdecimal with scale greater than 18

- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
Add support in "connect.cassandra.fetch.size" config, This config is in the documentation but was not being applied
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/392)
> Use fetchSize config in cassandra source

- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskTimestamp.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskTimeuuid.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceUtil.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/397)
> Adds test for fetchSize config

- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/400)
> fix the regex for matching the mqtt topic with the kcql defined value

- README.md
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CqlGenerator.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/Combiner.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceConnector.scala
- kafka-connect-coap/src/main/scala/com/datamountaineer/streamreactor/connect/coap/source/CoapSourceTask.scala
- kafka-connect-pulsar/src/main/scala/com/datamountaineer/streamreactor/connect/pulsar/ConsumerConfigFactory.scala
- kafka-connect-pulsar/src/main/scala/com/datamountaineer/streamreactor/connect/pulsar/config/PulsarConfigConstants.scala
- kafka-connect-pulsar/src/main/scala/com/datamountaineer/streamreactor/connect/pulsar/source/PulsarManager.scala
- kafka-connect-rethink/src/main/scala/com/datamountaineer/streamreactor/connect/rethink/config/ReThinkConfigConstants.scala
- kafka-connect-rethink/src/main/scala/com/datamountaineer/streamreactor/connect/rethink/config/ReThinkSourceConfig.scala
- kafka-connect-rethink/src/main/scala/com/datamountaineer/streamreactor/connect/rethink/config/ReThinkSourceSettings.scala
- kafka-connect-rethink/src/main/scala/com/datamountaineer/streamreactor/connect/rethink/source/ReThinkSourceTask.scala
- kafka-connect-rethink/src/test/scala/com/datamountaineer/streamreactor/connect/rethink/config/TestReThinkSinkConstants.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/401)
> Fix batch size

- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/KElasticClient.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticConfig.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticConfigConstants.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticSettings.scala
- kafka-connect-elastic6/src/test/scala/com/datamountaineer/streamreactor/connect/elastic6/TestElasticBase.scala
- kafka-connect-elastic6/src/test/scala/com/datamountaineer/streamreactor/connect/elastic6/TestElasticConfig.scala
- kafka-connect-elastic6/src/test/scala/com/datamountaineer/streamreactor/connect/elastic6/TestElasticWriter.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/404)
> Allow For HTTP Basic Auth for ES6 Http Client

- README.md
- gradle.properties
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/ElasticJsonWriter.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/ElasticSinkTask.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/ElasticWriter.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/KElasticClient.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/Transform.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/TransformAndExtractPK.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/config/ElasticConfig.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/config/ElasticConfigConstants.scala
- kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/config/ElasticSettings.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/ElasticJsonWriter.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/ElasticSinkTask.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/KElasticClient.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticConfigConstants.scala
- kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticSettings.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/417)
> Bringing HTTP auth into ES 5.x connector

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/430)
> Inline git commands

- kafka-connect-kudu/build.gradle
- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/KuduConverter.scala
- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/sink/DbHandler.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/429)
> support null values in avro unions

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/432)
> getting the deps in-line with the common lib

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/433)
> printing the java source/target compatibility

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/434)
> setting scala compiler targets

- kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/RedisSinkTask.scala
- kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisMultipleSortedSetsTest.scala
Fixes #437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/438)
> Correcting multiple sorted set selection

- conf/jms-sink.properties
- conf/jms-source.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/439)
> remove connect.jms.queues from properties

- README.md
- gradle.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/442)
> release 1.1.0

- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/MongoWriter.scala
- kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/Transaction.scala
- kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/MongoWriterTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/446)
> fixed mongodb handling of KCQL PK

- build.gradle
- kafka-connect-cassandra/src/test/resources/logback-test.xml
- kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/config/RedisSinkSettings.scala
- kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/config/RedisSinkSettingsTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/451)
> BUG: Stop KCQL Set squashing duplicates

- kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/RedisSinkTask.scala
- kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisMultipleSortedSetsTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/460)
> Fix bug in handling multiple primary keys for sorted sets

- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/KuduConverter.scala
- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/sink/DbHandler.scala
- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/sink/KuduWriter.scala
- kafka-connect-kudu/src/test/scala/com/datamountaineer/streamreactor/connect/kudu/TestKuduWriter.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/467)
> json support

- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/utils/KeyUtils.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/TestCassandraJsonWriter.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/utils/KeyUtilsTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/471)
> Use correct field types while extracting from struct key (#470)

- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/sink/DbHandler.scala
This is a PR to address issue #475
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/476)
> Fix deprecated avro field defaultValue call

- gradle/wrapper/gradle-wrapper.properties
- kafka-connect-hive/connector/src/main/scala/com/landoop/streamreactor/connect/hive/package.scala
- kafka-connect-hive/it/build.gradle
- kafka-connect-hive/it/src/test/resources/hive_source_task.json
- kafka-connect-hive/it/src/test/scala/com/landoop/streamreactor/hive/it/HiveOrcTest.scala
- kafka-connect-hive/it/src/test/scala/com/landoop/streamreactor/hive/it/HiveSchemaTest.scala
- kafka-connect-hive/it/src/test/scala/com/landoop/streamreactor/hive/it/HiveSourceTest.scala
- kafka-connect-hive/it/src/test/scala/com/landoop/streamreactor/hive/it/HiveTests.scala
- kafka-connect-hive/it/src/test/scala/com/landoop/streamreactor/hive/it/HiveWithPartitionTest.scala
- kafka-connect-hive/it/src/test/scala/com/landoop/streamreactor/hive/it/PersonTestData.scala
Added hive integration tests for schemas and for hive source connector.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/479)
> Added tests for hive schema, and hive hive source.

- kafka-connect-hive/connector/src/main/scala/com/landoop/streamreactor/connect/hive/formats/ParquetHiveFormat.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/482)
> Fixing bug in parquet serde detection.

- gradle/wrapper/gradle-wrapper.properties
- kafka-connect-hive/connector/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/483)
> Fixed name of kafka hive artifact

- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/MongoSinkConnector.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/490)
> fix scaling on mongo to use max.tasks

- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/KuduConverter.scala
As issue https://github.com/Landoop/stream-reactor/issues/512 said, this pr supports kudu decimal type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/513)
> add kudu decimal support

- README.md
- build.gradle
- kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/sink/writer/JMSWriter.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/502)
> wrap session rollback in exception handler

- kafka-connect-hive/connector/src/main/scala/com/landoop/streamreactor/connect/hive/sink/HiveSinkConnector.scala
- kafka-connect-hive/connector/src/main/scala/com/landoop/streamreactor/connect/hive/source/HiveSourceConnector.scala
Printing props maybe included secrets. Don't print.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/514)
> Don't print props on startup

- gradle.properties
Let's make this the 1.2.0 release for consistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/518)
> Bump version to 1.2.0

- gradle.properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/520)
> Switch to 1.3.0-SNAPSHOT

- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/sink/KuduSinkTask.scala
- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/sink/KuduWriter.scala
When I insert into data to kudu, I got some out of order records in kudu, and I thought this is a bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/523)
> fix records out of order when insert

- .travis.yml
- README.md
- build.gradle
- gradle.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/535)
> Release prep 1.2.1

- conf/hive-sink.properties
- conf/hive-source.properties
- kafka-connect-hive/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/536)
> docs(kafka-connect-hive): Added README for Hive Connector

- README.md
- build.gradle
- issue_template.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/538)
> Updating some links

- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala
Add regex for matching shared subscriber topic pattern.
Issue #542
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/546)
>  Add shared subscriber support

- kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/sink/converters/TextMessageConverter.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/463)
> Fixed JMS missing text converter for KCQL's withformat TEXT

- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/sink/MqttWriter.scala
- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala
Add MQTT Dynamic Target support
* Kafka message key as mqtt topic
* json field as mqtt message
This PR will close #491 issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/545)
> Add MQTT Dynamic Target support

- kafka-connect-mqtt/src/test/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManagerTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/552)
> Fix shared topic regex for MQTT

- kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/MongoWriter.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/570)
> Closes the mongo client connection when the sink task is closed

- kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/sink/KuduWriter.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/560)
> Allows comma separated kudu master endpoints

- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/connection/MqttClientConnectionFn.scala
- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/590)
> Supports multi server MQTT connection

- build.gradle
- kafka-connect-redis/README.md
- kafka-connect-redis/build.gradle
- kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/RedisSinkTask.scala
- kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/GeoAddSupport.scala
- kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisGeoAdd.scala
- kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/config/ConfigGeoAddTest.scala
- kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisCacheTest.scala
- kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisGeoAddTest.scala
Implemented new RedisGeoAdd writer to add support for Redis GEOADD command.
Added unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/593)
> Added support for Redis GEOADD command.

- kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisWriter.scala
- kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisSslTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/594)
> Set TLS to true is ssl enabled

- kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisWriter.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/595)
> Only set jks if config is set

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/598)
> Fix ordering of connectors in readme

- issue_template.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/597)
> Fix typo in issue template

- kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpMonitor.scala
This PR fixes a small bug in the FTPMonitor that lead to slices sizes to be double what they should be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/600)
> Fix bug in FTPMonitor leading to the buffer being twice as big

- kafka-connect-hive/it/docker-compose.yml
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/ConfigurationBuilder.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/formats/OrcHiveFormat.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/formats/ParquetHiveFormat.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/kerberos/Kerberos.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/kerberos/KerberosLogin.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/parquet/StructMaterializer.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/parquet/StructWriteSupport.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/parquet/package.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/HiveSink.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/HiveSinkConnector.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/HiveSinkTask.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/HiveWriterManager.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/evolution/AddEvolutionPolicy.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/evolution/IgnoreEvolutionPolicy.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/evolution/NoopEvolutionPolicy.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/evolution/StrictEvolutionPolicy.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/partitioning/DynamicPartitionHandler.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/staging/OffsetSeeker.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/staging/StageManager.scala
- kafka-connect-hive/src/test/scala/com/landoop/streamreactor/connect/hive/ConfigurationBuilderTest.scala
sl4j
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/599)
> Avoid the scala StrictLogging since it causes runtime class clash with

- kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/AsyncFunctionLoop.scala
- kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/HiveSchemas.scala
- kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/parquet/StructWriteSupport.scala
- kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/sink/ValueConverter.scala
- kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/sink/evolution/StrictEvolutionPolicy.scala
- kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/sink/mapper/MetastoreSchemaAlignMapper.scala
- kafka-connect-hive-1.1/src/test/scala/com/landoop/streamreactor/connect/hive/sink/MapValueConverterTest.scala
- kafka-connect-hive/build.gradle
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/AsyncFunctionLoop.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/HiveSchemas.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/parquet/StructWriteSupport.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/ValueConverter.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/evolution/StrictEvolutionPolicy.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/mapper/MetastoreSchemaAlignMapper.scala
- kafka-connect-hive/src/test/scala/com/landoop/streamreactor/connect/hive/sink/MapValueConverterTest.scala
MapValueConverter. Fix for Hive 2.x to avoid loading ridiculous old
calcite-avatica bringing an old Jackson library in
> Fix for writing nested structures to Hive.Adds unit test for

- README.md
Update ReadME for JMS Task Parralelization Bug fix.
> Update ReadME.md for Release/1.2.6

- build.gradle
- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttConfig.scala
- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttConfigConstants.scala
- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttSinkSettings.scala
- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/sink/MqttSinkTask.scala
- kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/sink/MqttWriter.scala
- kafka-connect-mqtt/src/test/resources/test.avsc
- kafka-connect-mqtt/src/test/scala/com/datamountaineer/streamreactor/connect/mqtt/sink/TestMqttWriter.scala
added converter for mqtt sink connector.
we are using avro serialized messages in our mqtt system.
> converter for mqtt sink connector

- .gitignore
- README.md
- build.gradle
- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskTimestamp.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCqlGenerator.scala
added special case for unwrapped message for json format and key
> added json format and keys

- kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/source/config/HiveSourceConfigDef.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/source/config/HiveSourceConfigDef.scala
Adds the hive kerberos settings, and HDFS settings tot the config definition
> Kerberos support for the Hive source

- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTask.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManager.scala
Bug fix ensuring writers are only flushed when they are eligible to do so
> S3 Sink - Writer Commit Bug Fix

- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/formats/JsonFormatWriter.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/model/SinkData.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTask.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/ToAvroDataConverter.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/ToJsonDataConverter.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/ValueToSinkDataConverter.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/formats/JsonFormatWriterTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/FieldValueToStringConverterTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/MapSinkDataConverterTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/ToJsonDataConverterTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/ValueToSinkDataConverterTest.scala
Prevent null pointer exception in converters when maps are presented with null values
> Map null pointer fix

- kafka-connect-aws-s3/build.gradle
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/CommitPolicy.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/FileNamingStrategy.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/OffsetSeeker.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManager.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/storage/MultipartBlobStoreStorageInterface.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/storage/S3Writer.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/storage/StorageInterface.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/DefaultCommitPolicyTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/OffsetSeekerTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala
Altering S3 Sink offset reader to restrict to topic and partitions in order to further restrict the load on S3
> S3 Sink Offset Reader Optimisation

- kafka-connect-hive/build.gradle
- kafka-connect-hive/it/src/test/resources/hive_sink_task_partition_key-orc.json
- kafka-connect-hive/it/src/test/scala/com/landoop/streamreactor/hive/it/HiveOrcTest.scala
- kafka-connect-hive/it/src/test/scala/com/landoop/streamreactor/hive/it/StudentTestData.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/domain.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/formats/OrcHiveFormat.scala
- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/package.scala
- kafka-connect-hive/src/test/scala/com/landoop/streamreactor/connect/hive/HiveTableCreatorTest.scala
- kafka-connect-hive/src/test/scala/com/landoop/streamreactor/connect/hive/sink/HiveOrcSinkTest.scala
* Fixes to file size for Orc.
* Ensuring it is possible to use a numerical value as a partition key.
* Enhanced tests.
> Fixes to orc and partitioning

- kafka-connect-aws-s3/README-sink.md
- kafka-connect-aws-s3/README-source.md
- kafka-connect-aws-s3/build.gradle
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/auth/AwsContextCreator.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3Config.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDef.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettings.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/model/BucketPathPrefix.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTask.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTask.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/auth/AwsContextCreatorTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/formats/AvroFormatStreamReaderTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/formats/ParquetFormatStreamReaderTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/formats/TextFormatStreamReaderTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/model/BucketAndPrefixTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/OffsetSeekerTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3AvroWriterManagerTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3JsonWriterManagerTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3ParquetWriterManagerTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/BucketSetup.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/ResultReaderTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceListerTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/storage/MultipartBlobStoreOutputStreamTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/storage/MultipartBlobStoreStorageInterfaceTest.scala
Support default chain for S3 sink
Remove region configuration
Add init check performing simple list for S3 sink to fail fast
> Implementing default chain auth for S3 sink

- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/S3BucketReaderManager.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/S3BucketReaderManagerTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTaskTest.scala
Fixes the issue of offset being off by 1 for S3 Source.
> S3 source offset fix

- kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/RedisSinkTask.scala
After repair, it can be successfully published to the Redis channel
> Fix redis pubsub Writer

- kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/sink/config/HiveSinkConfigDef.scala
> Hive sink kerberos debug flag

- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTask.scala
Implemented fix suggested in #754
> Fix for issue #754

- kafka-connect-hbase/src/main/scala/com/datamountaineer/streamreactor/connect/hbase/StructFieldsExtractorBytes.scala
- kafka-connect-hbase/src/test/scala/com/datamountaineer/streamreactor/connect/hbase/StructFieldsExtractorBytesTest.scala
Replaces usages of non-synchronized SimpleDateFormat with DateTimeFormatter to alleviate race condition in StructFieldsExtractorBytes
Fix for issue #753
> #753 - Race condition in StructFieldsExtractorBytes

- kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/CassandraJsonWriter.scala
- kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/TestCassandraJsonWriter.scala
In order to improve debuggability of the Cassandra connector, this expands logging to include the table name.
This is a fix for issue: https://github.com/lensesio/stream-reactor/issues/636
> #636 - CassandraJsonWriter does not log the table name for InvalidQueryException

- README.md
docs: correct description of Cassandra Source.
> docs: correct description of Cassandra Source.

- kafka-connect-ftp/src/it/scala/com/datamountaineer/streamreactor/connect/ftp/source/EndToEnd.scala
- kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpSourceTask.scala
- kafka-connect-jms/src/it/scala/com/datamountaineer/streamreactor/connect/jms/source/JMSReaderTest.scala
This branch is for attempts to fix unstable tests, which are impacting our ability to merge changes.
> Test stabilisation

- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/config/S3SourceConfig.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/model/PartitionExtractorTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/reader/ResultReaderTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/reader/S3ReaderManagerTest.scala
Fixes typos in the code when extracting the configuration values for the PartitionExtractor configuration.
> Fixing PartitionExtractor config

- build.sbt
- kafka-connect-mqtt/src/fun/resources/logback.xml
- kafka-connect-mqtt/src/fun/resources/mosquitto.config
- kafka-connect-mqtt/src/fun/scala/com/datamountaineer/streamreactor/connect/MqttClientResource.scala
- kafka-connect-mqtt/src/fun/scala/com/datamountaineer/streamreactor/connect/MqttContainer.scala
- kafka-connect-mqtt/src/fun/scala/com/datamountaineer/streamreactor/connect/MqttTest.scala
Adds an MQTT e2e test to verify the dependencies work correctly in the Kafka Connect context.
> Add an E2E Test for MQTT Sink

- README.md
- kafka-connect-aws-s3/README-sink.md
- kafka-connect-aws-s3/src/it/resources/profiles/inttest1.yaml
- kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDef.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDefTest.scala
- project/Dependencies.scala
* By default use AWS client.
* Update docs.
> Switch to AWS client

- .github/workflows/build.yml
- .github/workflows/release.yml
- kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpMonitor.scala
- project/Dependencies.scala
- project/Settings.scala
Add dependency check stage to build.
Minor dependency tweaks to avoid CVEs.
> Add dependency check stage to build.

- .github/workflows/release.yml
Fixes to the GitHub actions pipeline to support the changes to the project structure and caching since last release.
> Release pipeline fixes

- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/config/ReadTextMode.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/config/S3SourceConfig.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/config/kcqlprops/ReadTextMode.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/config/kcqlprops/S3PropsKeyEnum.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/config/kcqlprops/S3PropsSchema.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/config/ReadTextModeTest.scala
- kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/config/kcqlprops/S3PropsSchemaTest.scala
- kafka-connect-common/src/main/scala/io/lenses/streamreactor/connect/config/kcqlprops/KcqlProperties.scala
- kafka-connect-common/src/main/scala/io/lenses/streamreactor/connect/config/kcqlprops/KcqlPropsSchema.scala
- kafka-connect-common/src/main/scala/io/lenses/streamreactor/connect/config/kcqlprops/PropsSchema.scala
- project/Dependencies.scala
This adds the configuration element for the KCQL Properties required within the S3 Source.
> Add schema capability for specifying kcql properties

- kafka-connect-aws-s3/src/fun/scala/io/lenses/streamreactor/connect/S3CompressionTest.scala
- kafka-connect-aws-s3/src/fun/scala/io/lenses/streamreactor/connect/S3Test.scala
- kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala
- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettings.scala
In order to ensure maximum compatibility with the S3 Source, set padding by default.
This will cause a change in behaviour to users upgrading.
**New Defaults**
* Default padding: LeftPad
* Default padding length: 12
> 337 - Enforce sink padding by default

- kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/InfluxDbWriter.scala
During JVM profiling, I noticed the memory usage of the influxdb sink connector consistently increasing. Investigation revealed that the influxDbWriter wasn't closing properly, leading to the memory issue.
> fix(influxdb): Modify influxDbWriter to address the memory issue

- project/Dependencies.scala
Cleaning up a few deps that are no longer needed.
> Remove unused deps

- kafka-connect-gcp-storage/src/main/scala/io/lenses/streamreactor/connect/gcp/storage/model/location/GCPStorageLocationValidator.scala
> Fix regex for bucket names to allow underscore

- project/Settings.scala
> #1021 - Update release version

- java-connectors/kafka-connect-azure-eventhubs/src/main/java/io/lenses/java/streamreactor/connect/azure/eventhubs/config/AzureEventHubsConfig.java
- java-connectors/kafka-connect-azure-eventhubs/src/main/java/io/lenses/java/streamreactor/connect/azure/eventhubs/config/AzureEventHubsConfigConstants.java
- java-connectors/kafka-connect-azure-eventhubs/src/main/java/io/lenses/java/streamreactor/connect/azure/eventhubs/mapping/SourceRecordMapper.java
- java-connectors/kafka-connect-azure-eventhubs/src/main/java/io/lenses/java/streamreactor/connect/azure/eventhubs/source/AzureEventHubsSourceTask.java
- java-connectors/kafka-connect-azure-eventhubs/src/main/java/io/lenses/java/streamreactor/connect/azure/eventhubs/source/BlockingQueueProducerProvider.java
- java-connectors/kafka-connect-azure-eventhubs/src/main/java/io/lenses/java/streamreactor/connect/azure/eventhubs/source/EventHubsKafkaConsumerController.java
- java-connectors/kafka-connect-azure-eventhubs/src/main/java/io/lenses/java/streamreactor/connect/azure/eventhubs/source/KafkaByteBlockingQueuedProducer.java
- java-connectors/kafka-connect-azure-eventhubs/src/test/java/io/lenses/java/streamreactor/connect/azure/eventhubs/mapping/SourceRecordMapperTest.java
- java-connectors/kafka-connect-azure-eventhubs/src/test/java/io/lenses/java/streamreactor/connect/azure/eventhubs/source/BlockingQueueProducerProviderTest.java
- java-connectors/kafka-connect-azure-eventhubs/src/test/java/io/lenses/java/streamreactor/connect/azure/eventhubs/source/EventHubsKafkaConsumerControllerTest.java
Address LensesBox compatibility issue (described in LC-135)
> Add config to get compatible with LensesBoxes' Topic Extractor

- kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/storage/AwsS3StorageInterface.scala
- kafka-connect-azure-datalake/src/main/scala/io/lenses/streamreactor/connect/datalake/storage/DatalakeStorageInterface.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/formats/writer/FormatWriter.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/CloudSinkTask.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/Exceptions.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/naming/CloudKeyNamer.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/naming/IndexFilenames.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/seek/IndexManager.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/seek/IndexManagerErrors.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/writer/Writer.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/writer/WriterManager.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/storage/StorageInterface.scala
- kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/storage/UploadError.scala
- kafka-connect-cloud-common/src/test/scala/io/lenses/streamreactor/connect/cloud/common/sink/seek/IndexManagerErrorsTest.scala
- kafka-connect-cloud-common/src/test/scala/io/lenses/streamreactor/connect/cloud/common/sink/seek/IndexManagerTest.scala
- kafka-connect-gcp-storage/src/it/scala/io/lenses/streamreactor/connect/gcp/storage/storage/GCPStorageStorageInterfaceTest.scala
- kafka-connect-gcp-storage/src/main/scala/io/lenses/streamreactor/connect/gcp/storage/storage/GCPStorageStorageInterface.scala
Fix GCP storage interface NPE issue.
> Error handling changes for clarity and debugging ease.

- .github/workflows/build.yml
previous variable was only set for a PR, however the release uses a tag trigger. This time it hardcodes lensesio
> Fix the release build

- build.sbt
fix for build tu use Gradle wrapper instead of gradle command
> changing to use gradlew for spotless

- java-connectors/kafka-connect-common/src/test/java/io/lenses/streamreactor/common/util/ListSplitterTest.java
* Fixing list splitter test
* Improving list splitter test with jassert
> Test Fix: List Splitter
