lensesio/stream-reactor

.gitignore
kafka-connect-druid/build.gradle
kafka-connect-druid/src/main/scala/com/datamountaineer/streamreactor/connect/druid/DruidSinkConnector.scala
kafka-connect-druid/src/main/scala/com/datamountaineer/streamreactor/connect/druid/DruidSinkTask.scala
kafka-connect-druid/src/main/scala/com/datamountaineer/streamreactor/connect/druid/config/DruidSinkConfig.scala
kafka-connect-druid/src/main/scala/com/datamountaineer/streamreactor/connect/druid/config/DruidSinkSettings.scala
kafka-connect-druid/src/main/scala/com/datamountaineer/streamreactor/connect/druid/writer/DruidDbWriter.scala
kafka-connect-druid/src/test/scala/com/datamountaineer/streamreactor/connect/druid/config/DruidSinkSettingsTest.scala
kafka-connect-druid/src/test/scala/com/datamountaineer/streamreactor/connect/druid/writer/WikipediaSchemaBuilderFn.scala

For some reasons, all the import statements not targeting java.* namespace had disappeared.
Are you open to contributions? This one is quite humble. Still we are a team in the UK planning to use Druid as a sink for some of our Kafka topics. We stumbled on this repo which looked like the best start to get going. Let me know your thoughts!

[kafka-connect-druid] now compiles

---

kafka-connect-cassandra/build.gradle
kafka-connect-druid/build.gradle
kafka-connect-hbase/build.gradle
kafka-connect-kudu/build.gradle

Fx classloader conflict wrt guava versions 12.0.1 and 16.0.1 that conflict with a guava function used in elastic sink plugin
REF: https://github.com/datamountaineer/stream-reactor/issues/71
Within the set of connectors provided, the following guava versions are in use through transient dependencies: 12.0.1, 16.0.1, 18.0 and 19.0. The elastic sink connector depends on a guava function that was not yet available in 12.0.1 and 16.0.1... so hence the up-step of those transient dependencies.

Fix guava classloader conflict

---

kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoConfig.scala
kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoSinkSettingsTest.scala

Fix typo in mongo sink settings: kqcl -> kcql.

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskSpecifyColumns.scala

Was working w/ Kafka Connect pushing data from Cassandra to a Topic
I was setting the` connect.cassandra.source.kcql` to the following `INSERT INTO idocs-topic SELECT json_doc FROM idocs_events PK idoc_event_ts` but all of the columns in the table were included in the data written to the Topic
Here is a possible fix that honors the columns in the SELECT

Select column fix

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/utils/CassandraUtils.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskSpecifyColumns.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/utils/TestSchemaConverter.scala

This PR is a possible fix for Issue 134 
When the KCQL `INSERT INTO idocs-topic SELECT json_doc, idoc_event_ts FROM idocs_events IGNORE idoc_event_ts PK idoc_event_ts ` is set then the result will only contain the `json_doc` column. The PK column `idoc_event_ts` will be retrieved but removed from the Struct. 
This is related to #133 
It allows the retrieval to only pull back the SELECT columns, allows the PK/timestamp column to be specified for handling offsets, and also allows the PK/timestamp column to be removed from what is placed on the Topic

Cassandra Source: remove ignore columns from the result set

---

.gitignore
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/utils/CassandraUtils.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskSpecifyColumns.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/utils/TestSchemaConverter.scala

This is mostly open for comments and discussion to further explore configuration to allow more flexibility in how the `SourceRecord` is created. This is based on our conversations over email.
This PR is a possible refactor that would allow withunwrap KCQL to be plugged into the Cassandra Source. Right now the `CassandraTableReader` (line 267) has a variable `withunwrap` set to false.
The idea would be to replace this line with 
```val withunwrap = settings.withunwrap```
when the KCQL is updated and if that is the route you decide to go. 
When this is true it would create a comma delimited list out of the column values.
This allows 
`SELECT colA, ts FROM event_table IGNORE ts PK ts `
to yield a String on the Kafka Topic that contains only the value of colA

Refactor to prepare for withunwrap KCQL capability

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/utils/CassandraUtils.scala

fixing timestamp null handling before formatting, one use case was updated_on, if column is not available at first insert of the record and we are also trying to fetch and perform actions on it, it should be held null if null there as other columns.

fixing timestamp null handling before formatting

---

kafka-connect-elastic/build.gradle
kafka-connect-elastic/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/ElasticJsonWriter.scala
kafka-connect-elastic/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/ElasticWriter.scala
kafka-connect-elastic/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/config/ElasticSettings.scala
kafka-connect-elastic/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/config/ElasticSinkConfig.scala
kafka-connect-elastic/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/config/ElasticSinkConfigConstants.scala
kafka-connect-elastic/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/indexname/CustomIndexName.scala
kafka-connect-elastic/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/indexname/IndexNameFragment.scala
kafka-connect-elastic/src/main/scala/com/datamountaineer/streamreactor/connect/elastic/indexname/package.scala
kafka-connect-elastic/src/test/scala/com/datamountaineer/streamreactor/connect/elastic/TestElasticBase.scala
kafka-connect-elastic/src/test/scala/com/datamountaineer/streamreactor/connect/elastic/TestElasticJsonWriter.scala
kafka-connect-elastic/src/test/scala/com/datamountaineer/streamreactor/connect/elastic/TestElasticWriter.scala
kafka-connect-elastic/src/test/scala/com/datamountaineer/streamreactor/connect/elastic/indexname/ClockFixture.scala
kafka-connect-elastic/src/test/scala/com/datamountaineer/streamreactor/connect/elastic/indexname/TestCustomIndexName.scala
kafka-connect-elastic/src/test/scala/com/datamountaineer/streamreactor/connect/elastic/indexname/TestIndexNameFragment.scala

The ElasticSearch connector is updated with:
- support for auto-generated time/date in index names; this is to create indexes per day instead of one ever-increasing index, as per the official guidelines on [Retiring Data](https://www.elastic.co/guide/en/elasticsearch/guide/current/retiring-data.html)
- support for custom document type for the messages to be saved; document types allow custom indexing policies

ElasticSearch connector with date in index and custom document type

---

build.gradle
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraSettings.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CqlGenerator.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCqlGenerator.scala

This is the initial outline of the approach to page through results using token of the partition key, thus enabling CQL that does not require ALLOW FILTER. 
http://docs.datastax.com/en/cql/3.1/cql/cql_using/paging_c.html
As part of this approach, moved the CQL generation to a new class
Based on the various config that affects the CQL generation, the following precedence for CQL generation modes is currently implemented:
- bulk
- INCREMENTALMODE in KCQL
- config
All existing capabilities should work even with this incomplete feature. 
There are two areas still in progress
- need to refactor `CassandraTableReader` offset so relies on `CqlGenerator` to determine type (date vs token)
- need to refactor `CassandraTableReader` to use tokenDefaultStatement vs tokenStatementWithOffset
UPDATE
- …

Cassandra Source: use paging technique to avoid ALLOW FILTER

---

kafka-connect-jms/src/main/java/com/datamountaineer/streamreactor/connect/converters/ByteArrayConverter.java
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfig.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfigConstants.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSSettings.scala

Added ConnectionFactory default
Add config to provide a default converter
Add byte array connect converter which handles optional to allow straight byte passthrough, set using value.converter.

JMSSource Default Options

---

kafka-connect-jms/build.gradle
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/JMSSessionProvider.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfig.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfigConstants.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSSettings.scala

Add configuration to provide subscription name
Bump JMS API to 2.0
Add logic to create a shared durable subscriber if destination is Topic and subscription name exists.

ISSUE 179 : Support Shared Durable Subscription on JMS 2.0 Topics

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraSettings.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CqlGenerator.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCqlGenerator.scala

This PR is an attempt to correct #190 
It reverts the `CqlGenerator` to using the BATCH in KCQL instead of fetch.size in the config
It adds a test to show that it is working correctly w/ CQL that uses the token/paging
The `connect.cassandra.fetch.size` was added to `CassandraSettings` since it was not available to the Cassandra Source connector before. However it is currently not used in the `CqlGenerator`.

Add Test with KCQL Batch 

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraSettings.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CqlGenerator.scala
kafka-connect-cassandra/src/test/resources/log4j.properties
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/TestConfig.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTaskTokenCql.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCqlGenerator.scala

This PR builds on #176 and #188
It allows users to configure a Cassandra Source via KCQL to pull data from Cassandra from a table with a partition key that is a UUID. It will then page through additions to the table using token(id)/paging technique as described here
http://docs.datastax.com/en/cql/3.1/cql/cql_using/paging_c.html
Sample KCQL
```INSERT INTO myTopic 
SELECT id, string_field FROM myTable 
PK id 
BATCH=100
INCREMENTALMODE=TOKEN

Cassandra Source: Token/page based CQL 

---

kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/KuduConverter.scala
kafka-connect-kudu/src/test/scala/com/datamountaineer/streamreactor/connect/kudu/TestKuduConverter.scala

Fix for Issue #205: DOUBLE fields from Avro schema are mapped to FLOAT in Kudu
Mapped Avro Double fields to Kudu Double columns.

Fixed Avro double fields mapping to Kudu columns

---

conf/mongodb-sink.properties

The mongodb-sink.properties file contains a typo in the KCQL configuration parameter. Instead of connect.mongo.**kc**ql, connect.mongo.**kq**cl is used.

Typo in mongodb-sink.properties KCQL parameter leads to BadRequest exception

---

kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/StructFieldsExtractor.scala
kafka-connect-influxdb/src/test/scala/com/datamountaineer/streamreactor/connect/influx/StructFieldsExtractorTest.scala

This only supports `yyyy-MM-DDTHH:mm:ss.SSSZ` timestamps. It is a trivial addition, any reason not to include it originally?

influx: support string timestamp

---

kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttConfig.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttConfigConstants.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttSourceSettings.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttSourceTask.scala
kafka-connect-mqtt/src/test/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttSourceSettingsTest.scala
kafka-connect-mqtt/src/test/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManagerTest.scala

High CPU on MQTT source #267 
added configuration option: 'polling.timeout'

fixed: high cpu on mqtt-source

---

.gitignore
kafka-connect-cassandra/build.gradle
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraConfig.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraConfigConstants.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraSettings.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/CassandraJsonWriter.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/TestConfig.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/TestCassandraJsonWriter.scala

See #270 
The use case of my company was to consume from a compacted topic and in cases where the message value is null, use the message key to delete the record from the cassandra table.
Please feel free to point me towards style and standards docs that I might have overlooked.

Issue 270 Support cassandra delete

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/JMSSessionProvider.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSSourceTaskTest.scala

Previously the JMS Source was set to use a transacted session which caused the acknowledge mode to be ignored.
Fixes #226

JMS source session not transacted so that client acking works.

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/JMSSourceTask.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSSourceTaskTest.scala

This PR moves the acking of messages to the `commit` interface of a Kafka Connect `SourceTask`. From [here](https://docs.confluent.io/current/connect/devguide.html#task-example-source-task) it appears that acking in the `commit` will give us at-least-once semantics.

JMS Acknowledge after messages have been processed by Kafka Connect

---

build.gradle
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/JMSSessionProvider.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSSettings.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/JMSSourceTask.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/TestBase.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/config/JMSSettingsTest.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSReaderTest.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSSourceTaskTest.scala

This PR introduces allowing for message selectors in the JMS connector consumers. 
There is also a fix for the message acking, it was only working if messages had been polled in the previous loop before a commit.

JMS Message selector + Fix for message acking

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraSourceTask.scala

Edits for the `bindAndFireTimebasedQuery` method to use java.time enhanced classes in Java 8 to handle timezones. This is related to the change addressed in issue #278

Cassandra Source: handle time zones when dealing w/ time slices

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/domain/JMSStructMessage.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSReaderTest.scala

An optional array where each element has an optional key and an optional value seems to make more sense as an optional Map. 
Could even make the map empty if there are no properties instead of making the Map optional - not entirely sure of the consequences of that though for users of the schema. 
What do you guys think?

Use a map to represent the properties field in the jms avro schema

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraSourceTask.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala

This is a proposed fix for #300 
Have tested it in our QA environment with 
- 40,000 per min
- poll interval = 1 sec
- batch size = 1000
- time slice = 10 sec (hard coded at the moment) 
From the logs you can still see that the internal queue grows from time to time but this seems to keep good steady flow.

FIX: eliminate "deadlock" in Cassandra Source querying

---

kafka-connect-jms/build.gradle

Change scope of dependency from 'compile' to 'testCompile'
Fixes #326

fix(kafka-connect-jms): ActiveMQ libs are only required at test-time

---

kafka-connect-jms/build.gradle
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/JMSSessionProvider.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/TestBase.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/config/JMSSettingsTest.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSReaderTest.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSSessionProviderTest.scala

JMS Consumers are only created when in 'source' mode and JMS Producers are only created when in 'sink' mode.
Refactored some of the supporting test code so that the ActiveMQ brokers are started on a free port if none is specified at construction time. This prevents port collisions between tests and allows tests to potentially be run in parallel.
Fixes #330

fix(kafka-connect-jms): Ensure JMSSessionProvider only creates JMS Consumers and JMS Producers when appropriate.

---

conf/ftp-source.properties
kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpMonitor.scala
kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpSourceConfig.scala
kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpSourceTask.scala
kafka-connect-ftp/src/test/scala/com/datamountaineer/streamreactor/connect/ftp/source/EndToEnd.scala
kafka-connect-ftp/src/test/scala/com/datamountaineer/streamreactor/connect/ftp/source/RegExTest.scala

Most of the times you don't want all files in a certain directory to be processed. Added support for filtering files via RegEx pattern to the FTP Connector. Makes it possible to tell the connector to select files that only match a certain pattern set in the config. Default behaviour is matching all.

Added support for filtering files via RegEx

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/JMSSourceTask.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSSourceTaskTest.scala

There is a problem using the Kafka Connect `commit()` method detailed [here](https://issues.apache.org/jira/browse/KAFKA-5716). We observed messages being acked when there was a task failure (eg. schema registry being unavailable) even though they had not been processed.
We have followed a suggested fix which is to override the more granular `commitRecord(SourceRecord record)` method and keep track of records that need to be committed.

Fix JMS connector message acking.

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/JMSSessionProvider.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/JMSSourceTask.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSSessionProviderTest.scala

Previously the JMS connector was not closing the connection to the broker when a source task was shut down which could cause issues when reconnecting.

Close connection to broker when shutting down a task.

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfig.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfigConstants.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSSettings.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/JMSSourceTask.scala

Quick fix to stop the high CPU usage in the connector (currently there is a tight loop around polling for messages as it hardly blocks). In the future we can introduce queues which consumers add messages to and probably then improve the acknowledgement mechanism.

Add a polling timeout to the JMS connector.

---

kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/ElasticJsonWriter.scala
kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/config/ElasticConfig.scala
kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/config/ElasticConfigConstants.scala
kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/config/ElasticSettings.scala
kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/ElasticJsonWriter.scala
kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticConfig.scala
kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticConfigConstants.scala
kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticSettings.scala

Adds a new config for choice a delimiter when concatenating fields to PK.
```
connect.elastic.pk.separator=-
```

Adds PK joiner separator for Elastic Sink 5 and 6

---

kafka-connect-elastic5/build.gradle
kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/ElasticJsonWriter.scala
kafka-connect-elastic5/src/main/scala/com/datamountaineer/streamreactor/connect/elastic5/config/ElasticConfigConstants.scala
kafka-connect-elastic5/src/test/scala/com/datamountaineer/streamreactor/connect/elastic5/TestElasticBase.scala
kafka-connect-elastic5/src/test/scala/com/datamountaineer/streamreactor/connect/elastic5/TestElasticWriter.scala
kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/ElasticJsonWriter.scala
kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticConfigConstants.scala
kafka-connect-elastic6/src/test/scala/com/datamountaineer/streamreactor/connect/elastic6/TestElasticBase.scala
kafka-connect-elastic6/src/test/scala/com/datamountaineer/streamreactor/connect/elastic6/TestElasticWriter.scala

1 - Adds pipeline option #266 
2 - Adds PK like id for insert operation
3 - Adds auto generator id for insert operation with consumed message info 
4 - Change pk separator default
5 - Update elastic4s version in ES5 connector

Updates ES connector

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/JMSSessionProvider.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/TestBase.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSSessionProviderTest.scala

The JMS connection was never closed when an exception was thrown when instantiating JMS connection provider (e.g. configuring producers or consumers). It was just hanging forever, not allowing to create a new connection with the same id and unnecessarily using ActiveMQ resources.
This PR fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/395)

Closing JMS connection on failing to instantiate JMS session provider

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraConfig.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraConfigConstants.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraSettings.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/CassandraJsonWriter.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/TestCassandraJsonWriterUnset.scala

feat(cassandra-sink): Add to cassandra-sink support json-unset
Add support to "unset" JSON fields in prepared statements ( see https://issues.apache.org/jira/browse/CASSANDRA-11424 ).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/402)

Add to cassandra-sink support json-unset

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraSourceTask.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTableReader.scala

When connector is in waiting interval step and you send "DELETE /connectors". Kafka connect worker has problem for stop thread.
And when connector is paused state and you send "DELETE /connectors". Kafka connect worker has problem for stop thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/391)

Connector DELETE in waiting interval step

---

kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/connection/MqttClientConnectionFn.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttSourceTask.scala
kafka-connect-mqtt/src/test/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManagerTest.scala
kafka-connect-mqtt/src/test/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttSourceTaskTest.scala

Fixes #419
- Refactored MqttManager: client is now created by MqttManager instead of MqttClientConnectionFn (necessary because callback is invoked before MqttClientConnectionFn returned the MqttClient, and subscribing moved to the onConnect callback.
- Changes to MqttSourceTask: no more implicit MqttSourceSettings: now explicitly passed to MqttManager instead of MqttClientConnectionFn
- Changes to MqttManagerTest: Added try-finally block so MqttManager is closed even when tests fail. Added test that verifies that manager resubscribes after reconnect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/425)

Implemented resubscribe on reconnect logic

---

kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/RedisSinkTask.scala
kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/config/RedisSinkSettings.scala
kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/RedisSinkTaskTest.scala

**Problem description:**
When using a KCQL statement that uses the Sorted Set mode, this is not being picked up by the RedisSinkTask, more specifically, not by this check: https://github.com/Landoop/stream-reactor/blob/master/kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/RedisSinkTask.scala#L75
This seems to be due to the fact that the primary keys array is an empty array, rather than it being null when no primary keys are provided in the KCQL statement. This results in the application throwing an exception stating that no writers were set per https://github.com/Landoop/stream-reactor/blob/master/kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/RedisSinkTask.scala#L100
This PR includes a patch for this issue, …

Bugfix for detecting Sorted Set mode

---

build.gradle

As discussed per https://github.com/Landoop/stream-reactor/issues/437#issuecomment-392737275, adding the link4j dependency to the main gradle file would benefit projects not containing this dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/453)

Adding Link4J dependency to main gradle file

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/JMSSessionProvider.scala

The JMS sink is not sending the password because of the wrong InitialContext argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/455)

Fixed JMS missing password on authentication process (on lookup)

---

build.gradle
kafka-connect-redis/README.md

Just adding a note to the README to notify users that this plugin cannot be used for sinking schemaless JSON to Redis.
This would have saved me quite some time as this is an absolute requirement for our project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/457)

Document lacking support for schemaless JSON

---

build.gradle
kafka-connect-mongodb/build.gradle
kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoSettings.scala
kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/KeysExtractor.scala
kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/MongoWriter.scala
kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/KeysExtractorTest.scala
kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/MongoWriterTest.scala

This fixes KCQL "PK" clauses where there are more than one key listed:  https://github.com/Landoop/stream-reactor/issues/450
It also adds the ability to use "embedded keys", where the keys are embedded in sub-documents in the input.  (For example, so you can do PK clauses like "PK person.address.streetNumber" or something like that.)
This PR depends on https://github.com/Landoop/kafka-connect-common/pull/25, which ensures the proper ordering of the multi-key PK clauses.  Please see that PR as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/473)

Fix and enhance mongodb sink key handling (Fix for #450)

---

kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/sink/DbHandler.scala

Auto-creating a kudu table with DISTRIBUTEBY enabled created an unnecessary
unbounded range partition.
Fixes #472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/474)

fix(kudu): Eliminate unbounded range partition

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraConfigConstants.scala
kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/CassandraJsonWriter.scala

At this moment there is no way to use primitive types in `connect.cassandra.delete.struct_flds` if schema type is `Schema.Type.STRING`. Also we cannot use `connect.cassandra.delete.struct_flds` without definition if `connect.cassandra.delete.statement` was defined because we got `InvalidQueryException: Invalid unset value for column` at runtime. I suggest to use default value of `connect.cassandra.delete.struct_flds` for primitive types. On the other hand if we define `connect.cassandra.delete.struct_flds` it represents string key as JSON.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/487)

Support primitive types in `connect.cassandra.delete.struct_flds`

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/CassandraJsonWriter.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/sink/TestCassandraJsonWriter.scala

The purpose of this PR:
* fixed problem of insert/delete order
* fixed problem of async writes with the same topic partition
* added test for #487
Example of insert/delete order problem (same problem when use async insert/delete per record it may cause race condition)
```scala
`CassandraJsonWriter.write` method:
insert(records.filter( r => Option(r.value()).isDefined) )
delete(records.filter( r => Option(r.value()).isEmpty) )
```
it seems like a bug, what if I have the next records:
```scala
val record1 = new SinkRecord("TOPIC", 0, Schema.INT64_SCHEMA, idField, Schema.STRING_SCHEMA, s"""{"id": "$idField", "name": "test"}""", 1)
val record2 = new SinkRecord("TOPIC", 0, Schema.INT64_SCHEMA, idField, null, null, 1)
val record3 = new SinkRecord("TOPIC", 0, Schema.INT64_SCHEMA, idField, …
```

Sequential processing of the messages per topic partition

---

kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisCache.scala
kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisFieldsKeyBuilder.scala
kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisCacheTest.scala

Previously, if you were trying to use nested fields in ksql like that: 
```
connect.redis.kcql=INSERT INTO user.state. SELECT * FROM user.state PK auth.userId, connectionId
```
You would have met following error:
```
[2018-07-24 14:25:05,696] ERROR WorkerSinkTask{id=RedisSinkConnector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:517)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
at …
```

Add ability to use nested field as PK for RedisCache

---

kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoConfig.scala
kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoConfigConstants.scala
kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoSettings.scala
kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/converters/SinkRecordConverter.scala
kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/KeysExtractor.scala
kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/SinkRecordToDocumentTest.scala
kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoSettingsTest.scala
kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/converters/SinkRecordConverterTest.scala
kafka-connect-mongodb/src/test/scala/com/datamountaineer/streamreactor/connect/mongodb/sink/KeysExtractorTest.scala

For sinking JSON messages to mongodb, this adds the ability to configure a list of fields that should 
be converted to ISODate on insertion.  Without this patch, the 
fields are added as strings, which can be problematic when dealing with 
time offsets.
New configuration field is: 
connect.mongo.json_datetime_fields.
Description (added to documentation):
List of fields that should be converted to ISODate on Mongodb insertion 
(comma-separated field names).  For JSON topics only.  Field values may be 
an integral epoch time or an ISO8601 datetime string with an offset (offset 
or 'Z' required).  If string does not parse to ISO, it will be written as a 
string instead.
Subdocument fields can be referred to as in the following examples: 
"topLevelFieldName",
"topLevelSubDocument.FieldName", …

Convert json date time fields to MongoDB datetime values

---

kafka-connect-kudu/src/main/scala/com/datamountaineer/streamreactor/connect/kudu/sink/DbHandler.scala

in `com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler`:createTables, there is no need for the outer loop on `subjects`. And the loop on `subjects` will lead to creating same table multiple times, which will be failed for the second time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/510)

fix bug: creating kudu table multiple times

---

kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/InfluxBatchPointsBuilder.scala
kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/ValuesExtractor.scala

- InfluxDB does not support arrays so we extract each element of
the array and write them as new fields in InfluxDB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/522)

Support array type in InfluxDB connector

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/source/CassandraTypeConverter.scala
kafka-connect-cassandra/src/test/scala/com/datamountaineer/streamreactor/connect/cassandra/source/TestCassandraTypeConverter.scala

- Fixed Set support on Cassandra Source Connector
- One test case added
Fixes #492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/532)

fix(kafka-connect-cassandra): Set support on Cassandra Source Connector

---

kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisCache.scala
kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisInsertSortedSet.scala
kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisMultipleSortedSets.scala

It is crucial in my use case for Redis keys to have TTL, so I add it.
I'm not sure if it is the right way or not. but please merge it if it is.
Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/541)

Adds ttl support to redis

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/domain/JMSStructMessage.scala

Oracle Advanced Queues are sending JMS messages where some properties have null values. This pull request adds support for this behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/551)

Fix JMS messages containing null values in properties

---

kafka-connect-elastic6/src/main/scala/com/datamountaineer/streamreactor/connect/elastic6/config/ElasticConfigConstants.scala

to prevent NullPointerException when using HTTP without setting
authentication credentials.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/557)

Set http basic auth user/password to empty strings

---

kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraSettings.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/561)

Fixes the comparison for Cassandra timestamp type during connector setup

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfig.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfigConstants.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSSettings.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/sink/converters/JMSHeadersConverterWrapper.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/sink/writer/JMSWriter.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/TestBase.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/sink/writer/JMSWriterTest.scala

New configuration option `connect.jms.headers` to define custom static JMS
headers (`JMSType`, `JMSExpirationTime`, `JMSPriority`, `ReplyTo` etc.) for each JMS destination.
Parameter is optional so connector configuration is backward compatible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/576)

Custom Static JMS headers support

---

kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/RedisSinkTask.scala
kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/PubSubSupport.scala
kafka-connect-redis/src/main/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisPubSub.scala
kafka-connect-redis/src/test/scala/com/datamountaineer/streamreactor/connect/redis/sink/writer/RedisPubSubTest.scala

This pr adds a redis pubsub sink.
You chose a "channel" field which decides which redis channel to publish into.
This would allow you to use redis as a filter/router for a kafka queue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/landoop/stream-reactor/591)

Add redis pubsub sink

---

kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpMonitor.scala

Update `FTPMonitor` to ensure FTPS compatibility by enforcing private mode.
This is made by issuing two cmd in the connection flow of the FTP client. `PBSZ 0` and `PROT P` as metionned in the [original spec of the ftp over tls](https://tools.ietf.org/html/rfc4217)
Based on this [blog post](http://eng.wealthfront.com/2016/06/10/connecting-to-an-ftps-server-with-ssl-session-reuse-in-java-7-and-8/)

Update connector to use ftps protocol

---

kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/TimestampValueCoerce.scala
kafka-connect-influxdb/src/test/scala/com/datamountaineer/streamreactor/connect/influx/ValuesExtractorMapTest.scala

This PR is proposal to fix issue #625 
-  It assumes Unix timestamps in seconds if type is double and coerce to Long with milliseconds precision 
- Add test

Add support to Unix timestamp as double in the InfluxDB Sink connector

---

kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttConfig.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttConfigConstants.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttSourceSettings.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttSourceConnector.scala
kafka-connect-mqtt/src/test/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttSourceConnectorTest.scala

Add an option called `connect.mqtt.share.replicate`.
When enabled, the messages published to shared subscriptions are
distributed over all tasks. Therefore, the work generated by a KCQL
instruction with a shared subscription is now divided over all tasks. It
is the job of the MQTT broker to load balance the messages to the
connected tasks.

feat(MQTT): replicate shared subscription to all tasks if enabled

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfig.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfigConstants.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSSettings.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/JMSSourceTask.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/readers/JMSReader.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSReaderTest.scala

Ack the JMS messages was not always possible. Also there was an issue with producing the messages to Kafka out of order from the JMS queue
This change makes sure the
* Queue messages order are retained when published to Kafka (although they might be routed to different partitions)
* Ack happens for each message. This is a change from previous behaviour.
* Records which fail to be committed to Kafka are not ack-ed on JMS side

JMS Source fixes

---

kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfig.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/config/JMSConfigConstants.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/JMSSourceConnector.scala
kafka-connect-jms/src/main/scala/com/datamountaineer/streamreactor/connect/jms/source/JMSSourceTask.scala
kafka-connect-jms/src/test/scala/com/datamountaineer/streamreactor/connect/source/JMSSourceConnectorTest.scala

Allow the connector to respect the tasks.max value provided if the user `connect.jms.scale.type`

JMS Source tasks parallelization

---

kafka-connect-rabbitmq/src/main/scala/com/datamountaineer/streamreactor/connect/rabbitmq/client/RabbitMQClient.scala

Add support for client virtual host configuration

#651 - RabbitMQ Connector doesn't configure client to use virtual host

---

kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/converters/SinkRecordConverter.scala

Fixes #658 by also checking for `java.math.BigDecimal`. Since the code uses `java.math.BigDecimal` as well as the scala `BigDecimal` in several places, I opted to add a new case for the `java.math.BigDecimal` instead of replacing the scala `BigDecimal` case.

Add case for java.math.BigDecimal type with mongodb sink.

---

build.gradle
kafka-connect-azure-documentdb/build.gradle

- Azure is deprecating v1.x of the API on May 30th, 2020. Updating to avoid issues.
resolves #665

updated documentDBversion

---

kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/HadoopConfigurationExtension.scala
kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/sink/HiveSinkTask.scala
kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/source/HiveSourceTask.scala
kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/source/config/HiveSourceConfig.scala
kafka-connect-hive-1.1/src/main/scala/com/landoop/streamreactor/connect/hive/source/config/HiveSourceConfigConstants.scala
kafka-connect-hive-1.1/src/test/scala/com/landoop/streamreactor/connect/hive/source/HiveSourceTest.scala
kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/HadoopConfigurationExtension.scala
kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/source/HiveSourceTask.scala
kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/source/config/HiveSourceConfig.scala
kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/source/config/HiveSourceConfigConstants.scala
kafka-connect-hive/src/test/scala/com/landoop/streamreactor/connect/hive/source/HiveSourceTest.scala

The hive source was missing secured connection support. This has been raised by a few users of it.
The PRs brings the Kerberos support in the Hive sink to the source.

Kerberos support for the Hive source

---

kafka-connect-ftp/build.gradle
kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/ConnectFileMetaDataStore.scala
kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpMonitor.scala
kafka-connect-ftp/src/main/scala/com/datamountaineer/streamreactor/connect/ftp/source/FtpSourceTask.scala
kafka-connect-ftp/src/test/resources/log4j.properties
kafka-connect-ftp/src/test/scala/com/datamountaineer/streamreactor/connect/ftp/source/ManyFilesTest.scala

FTP: respect "connect.ftp.max.poll.records" when reading slices.

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/formats/BytesFormatWriter.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/formats/BytesFormatWriterTest.scala

Ensures that bytes mode on the sink outputs the complete size as bytes.

S3 Sink Byte Fixes

---

kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/formats/OrcHiveFormat.scala

When sinking with ORC the file is not created automatically. Therefore getting the file status to get the file size should check for the file presence. The code changes the approach to return 0 if the file does not exists. This fixes the unit tests and the prospect issue.

ORC Sink Failure

---

kafka-connect-hive/src/main/scala/com/landoop/streamreactor/connect/hive/package.scala

Kafka Connect gets field names in uppercase whilst Hive converts everything to lowercase. When the connector tries to get the value of a partition key (in this case sl_rzbk) Kafka Connect throws an exception because it doesn't know a field with that name

Fix partition fields lookup

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/formats/CsvFormatStreamReader.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/formats/TextFormatStreamReader.scala

Resolution for inability of connector to determine line breaks when the connector is run on certain docker images.

CLOUD-1340 - Using scala source instead of Scanner

---

kafka-connect-influxdb/build.gradle

Bump the influxdb-java dependency. In particular, need a fix introduced in influxdb-java 2.16 which skips fields with NaN and Infinity values when writing to InfluxDB.

Bump influxdb-java from version 2.9 to 2.21

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/auth/AwsContextCreator.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3Config.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDef.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettings.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTask.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManager.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala

This PR introduces multiple properties for error handling and retry.
``connect.s3.error.policy``
Specifies the action to be taken if an error occurs while inserting the data.
There are three available options:
NOOP - the error is swallowed
THROW - the error is allowed to propagate.
RETRY - The exception causes the Connect framework to retry the message. The number of retries is set by connect.s3.max.retries.
All errors will be logged automatically, even if the code swallows them.
``connect.s3.max.retries``
The maximum number of times to try the write again.
``connect.s3.retry.interval``
The time in milliseconds between retries.
``connect.s3.http.max.retries``
Number of times to retry the http request, in the case of a resolvable error on the server side.
``connect.s3.http.retry.interval`` …

S3 Connector Error Handling and Retry Logic

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTask.scala

Because the startup validation is unnecessary and expensive, and will happen naturally later on in the flow.

Remove bucket validation on startup

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDef.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettings.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3FlushSettings.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/config/S3SinkConfig.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/S3SinkConfigDefBuilderTest.scala

This PR amends the default values for the AWS S3 Sink Flush (Size, Count and Interval).
The new default values are
```
WITH_FLUSH_SIZE = 500000000
WITH_FLUSH_INTERVAL = 3600
WITH_FLUSH_COUNT = 50000
```
In addition the new property has been introduced
`connect.s3.disable.flush.count=true`
So that, if necessary, the flush count can be disabled to revert to the previous behaviour.

Enabling simpler management of default flush values in S3 Sink connector

---

.github/workflows/build.yml
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/formats/ParquetFormatWriter.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManager.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/writer/CommitState.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/writer/S3Writer.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/storage/JCloudsStorageInterface.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/storage/StorageInterface.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/formats/ParquetFormatWriterStreamTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/formats/TextFormatWriterTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManagerTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/utils/RemoteFileTestHelper.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTaskTest.scala

Fixes
* ensure Parquet writer tracks written data effectively
* keep last seeked offset in sink
* avoid NPE in preCommit
* avoid test reports being added to the PR in github actions

Parquet data size flushing fixes

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/model/PartitionField.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/model/PartitionSpecifier.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/model/SinkData.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/FileNamingStrategy.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTask.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3AvroWriterManagerTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3JsonWriterManagerTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3ParquetWriterManagerTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala

This PR adds date partitioning into the S3 Sink.
The formats can be specified using the preconfigured strings from https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
An example of the KCQL configuration:
`insert into $BucketName:$PrefixName select * from $TopicName PARTITIONBY _date.uuuu,_date.LL,_date.dd WITHPARTITIONER=Values WITH_FLUSH_COUNT = 1`
This will partition by year/month/day for example 2020/10/25

S3 Sink - Date Partitioning

---

project/Dependencies.scala

This is required in order for the AWS client to assume roles using a web identity token, like you might have for a pod with an IAM role linked service account in an EKS cluster.
This is in the same vein as [this PR](https://github.com/lensesio/secret-provider/pull/25) against the `secret-provider` repository.

Add aws sts dependency.

---

.github/workflows/build.yml
.github/workflows/release.yml

Include release workflow to create a new release when a new tag is created.
* The release workflow will call the build.yaml workflow using the `workflow_call` pattern, so all tests and builds must be a success before publishing the new release.
* Tags must follow semantic versioning `MAJOR.MINOR.PATCH` to create a new release. To create a pre-release, add `+(alpha|beta|rc).<build>`

feat: introduce release process as gh workflow

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/auth/AwsS3ClientCreator.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/auth/JCloudsS3ContextCreator.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3Config.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDef.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettings.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/ConnectionPoolConfigTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDefTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettingsTest.scala

This adds the following property to the S3 connector:
`connect.s3.pool.max.connections`
This can be set to a value to control the connection pool's max connections value.
The default value varies according to the library used.  For the AWS library it is 50, for Jclouds it is 30.
To use the default you can avoid defining this property, alternatively define it as -1.

Add connection pool config to S3 Connector

---

kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttConfig.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttConfigConstants.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/config/MqttSourceSettings.scala
kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/source/MqttManager.scala

This should resolve issue: #766 
This introduces a new configuration parameter:
`connect.mqtt.process.duplicates`
By default this is set to false (the current behaviour).
By setting to 'true' you instruct the MQTT source connector to process duplicates.

Allow toggling the skipping of MQTT Duplicates

---

kafka-connect-mqtt/src/main/scala/com/datamountaineer/streamreactor/connect/mqtt/sink/MqttSinkConnector.scala
kafka-connect-mqtt/src/test/scala/com/datamountaineer/streamreactor/connect/mqtt/sink/MqttSinkConnectorTest.scala

To fix #867
No additional configuration is required.

Functionality to ensure unique MQTT Client ID is used for MQTT sink

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDef.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettings.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/model/PartitionExtractor.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/model/PollResults.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/model/SourceData.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTask.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/config/S3SourceConfig.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/reader/ReaderCreator.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/reader/ResultReader.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDefTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettingsTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/model/PartitionExtractorTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/reader/ResultReaderTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/reader/S3ReaderManagerTest.scala

This introduces new functionality to ensure that the original partitions are passed back into Kafka Connect when reading from the source.
The following two new properties are introduced:
``connect.s3.source.partition.extractor.type`` - Can either be `heirarchical` (which matches the topic/partition/offset.json format the sink uses by default) or `regex` (where you can supply a custom regular expression to extract the partition).
``connect.s3.source.partition.extractor.regex`` - If using regex, the regex to use to parse the file path and retrieve the partition.  Only one lookup group is expected.  For an example regex please see the regex for hierarchical, which is in the [source code](https://github.com/lensesio/stream-reactor/blob/3a8d972b4f9b76997ab6e47bc7c2a10ccca8b8b9/kafka-connect-aws …

Source: Retain partitions from filename or regex

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/ToJsonDataConverter.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/ToJsonDataConverterTest.scala

During the deployment of a mongo cdc using the `MongoSourceConnector` we found that certain generated records where containing null elements in the generated array. 
This caused the S3 Sink connector to fail and we managed to solve the problem by patching the connector with the provided conversion to our fork. 
Porting here the fix that we used

adding test and Null conversion

---

kafka-connect-common/src/main/java/com/datamountaineer/streamreactor/connect/json/SimpleJsonConverter.java
kafka-connect-common/src/test/java/com/datamountaineer/streamreactor/connect/json/SimpleJsonConverterTest.java
project/Dependencies.scala

Fixes #911 
Should be using .equals instead of using java reference equality otherwise identical schemas will be flagged as mismatched.
Also re-enabling the java tests for this class.

0911 - Identical schemas should not mismatch

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3AvroWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3JsonWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3ParquetWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManagerTest.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/PaddingStrategySettings.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDef.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettings.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/FileNamingStrategy.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/PaddingStrategy.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/config/S3SinkConfig.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDefTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettingsTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/model/S3StoredFileTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/CommittedFileNameTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/PaddingStrategyTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/seek/LegacyOffsetSeekerTest.scala

Add option to add a padding so that files can be restored in order by the source
This PR introduces 2 new configuration options:
**connect.s3.padding.strategy**
"LeftPad" - add 0's to the left, eg 5 padded to 3 digits becomes 005
"RightPad" - add 0's to the right, eg 5 padded to 3 digits becomes 500
"NoOp" - this is the default value, and retains the legacy behaviour
**connect.s3.padding.length**
Specify the length of the string you wish to pad to.  Default, if not set, is 8.  If `connect.s3.padding.strategy` is not set then this property will be ignored.

S3 Sink - Enable Padding for Partition/Offset in filenames

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3AvroWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3JsonWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3ParquetWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManager.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/config/S3SinkConfig.scala

Enable wildcard syntax to support multiple topics without additional configuration via KCQL.
Following this PR you will be able to do:
**`connect.s3.kcql`** 
```
insert into $BucketName:$PrefixName select * from `*`
```

S3 Sink - Wildcard Topics Support

---

project/Settings.scala
project/assembly.sbt

This is the contents of the manifest (testing locally)
```
Manifest-Version: 1.0
Specification-Title: kafka-connect-common
Specification-Version: 1.1-SNAPSHOT
Specification-Vendor: io.lenses
Implementation-Title: kafka-connect-common
Implementation-Version: 1.1-SNAPSHOT
Implementation-Vendor: io.lenses
Implementation-Vendor-Id: io.lenses
Git-Commit-Hash: 0be0c01b7e2347c9e969422b61ecdf8bab90e852
Git-Repo: git@github.com:lensesio/stream-reactor.git
Git-Tag: n/a
Kafka-Version: 3.3.0
StreamReactor-Version: 1.1-SNAPSHOT
StreamReactor-Docs: https://docs.lenses.io/5.0/integrations/connectors/s
tream-reactor/
```

Return the manifest to its former glory.

---

project/Dependencies.scala
project/Settings.scala
project/plugins.sbt

- Remove obsolete repository "codejars"
- Add sbt-license-report plugin so we can provide BOM for 3rd party libraries and their licenses
- Set version to 4.2 as it had remained to 1.0 to assist with local builds
- Switch back copyright to Lenses.io Ltd
[OPS-2177]
[OPS-2177]: https://landoop.atlassian.net/browse/OPS-2177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Build system updates and improvements

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDef.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettings.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigDefTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettingsTest.scala
kafka-connect-common/src/main/scala/com/datamountaineer/streamreactor/common/config/base/const/TraitConfigConst.scala
kafka-connect-common/src/main/scala/com/datamountaineer/streamreactor/common/config/base/traits/LogOverrideSettings.scala
kafka-connect-common/src/test/scala/com/datamountaineer/streamreactor/common/config/base/traits/LogOverrideSettingsTest.scala
kafka-connect-common/src/test/scala/com/datamountaineer/streamreactor/common/config/base/traits/TestLoggerConfig.scala

Allow configuring logging via connector configuration - (currently S3 connector only)
This introduces a new property for the AWS S3 connector:
`connect.s3.log.level.override`
The values this can take are: `DEFAULT`, `OFF`, `ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE`, `ALL`.  If not specified `DEFAULT` will be used and the logging behaviour will be unchanged from previous releases.
This impacts the log levels of the connector code (anything under the packages `io.lenses` and `com.datamountaineer`).
This allows configuration of the logging levels for systems eg MSK where the Kafka Connect logging API is not available.

Connector Logging Configuration

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/formats/reader/ParquetFormatStreamReader.scala
project/Dependencies.scala

Allows Parquet INT96 to be read as a fixed size array. Otherwise, it fails at runtime.
Updates the dependency on parquet to 1.13.1

Parquet INT96 support

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3AvroWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3JsonWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3ParquetWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTaskTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/storage/AwsS3StorageInterfaceTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/utils/S3ProxyContainerTest.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/ConnectorTaskId.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTask.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/config/LocalStagingArea.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/distribution/PartitionHasher.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/state/OpenS3SourceTaskState.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/utils/TimestampUtils.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/ConnectorTaskIdTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/TaskDistributorTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/config/LocalStagingAreaTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/seek/IndexManagerTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/seek/LegacyOffsetSeekerTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/distribution/PartitionHasherTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/reader/ReaderManagerTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/storage/AwsS3DirectoryListerTest.scala
project/plugins.sbt

Fix the bug where the ConnectorTaskId had the task number, and the maxtasks values reversed. This created a runtime exception on PartitionHasher (division by zero).
Removes the ConnectorTaskId trait and creates a case class. There was no reason to default when the name or TASK_INDEX properties were missing.
Adds the unit test around the ConnectorTaskId to check the values for max tasks and task number.

Fix division by zero bug

---

kafka-connect-common/src/main/scala/com/datamountaineer/streamreactor/common/config/base/traits/ConsistencyLevelSettings.scala
kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/config/InfluxConfig.scala
kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/config/InfluxSettings.scala
kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/converters/InfluxPoint.scala
kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/InfluxBatchPointsBuilder.scala
kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/InfluxDbWriter.scala
kafka-connect-influxdb/src/test/scala/com/datamountaineer/streamreactor/connect/influx/InfluxBatchPointsBuilderTest.scala
kafka-connect-influxdb/src/test/scala/com/datamountaineer/streamreactor/connect/influx/config/InfluxSettingsTest.scala
project/Dependencies.scala

Upgrading to use the InfluxDB2 client.
Note: This doesn't yet support Influxdb2 connections but uses the InfluxDB1 compatibility.
This lays the groundwork for supporting both InfluxDB releases within the same module.

Upgrade to Influxdb2 client

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/config/S3SourceConfig.scala

If not specified in the KCQL statement, the s3 source limits the number of records returned on each poll to 1024. This is a small number and impacts throughput. The change changes the default to 10000

S3 source default records per poll 

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/ConnectorTaskId.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManager.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/seek/IndexFilenames.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/distribution/PartitionSearcher.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/reader/PartitionDiscovery.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/state/ReaderManagerBuilder.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/state/S3SourceBuilder.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/storage/AwsS3DirectoryLister.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/reader/PartitionDiscoveryTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/state/ReaderManagerBuilderTest.scala

This PR addresses the bug in the S3 source not distributing the workload. The issue lies with AwsS3DirectoryLister and the check on ConnectorTaskId:owns. The check was applied at the root and intermediary paths to the location, and if it was none, the search was stopped. However, the check should happen when it reaches the recursive/nested level.
PartitionDiscovery now logs the connector task details.
ConnectorTaskId.show was also changed to output the task count to help debug when multiple tasks run on the same connect worker.
S3SourceBuilder logic has changed when a reader manager is created. The partition search provides the root S3 location and a full path to the partition. The partition path becomes the prefix to align with the S3 listing interface. Since the connector offsets keep …

S3 source work distribution bug

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/S3ConfigSettings.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/config/S3SourceConfigTests.scala

The default is changed from 3 to 0. This is done because most of the time the S3 location points to the parent partition "folder"

S3 source default partition recursive level

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManager.scala

The error is quite cryptic when the KCQL statement source does not match the input topics on the sink configuration. The PR changes the error and also provides an indication of how to fix it.

Improve error message on misaligned topic configs

---

kafka-connect-aws-s3/README-sink.md
kafka-connect-aws-s3/README-source.md
kafka-connect-aws-s3/src/fun/scala/io/lenses/streamreactor/connect/Configuration.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskAvroEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskDeprecatedTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskJsonEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskParquetEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceAvroEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceJsonEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceParquetEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTaskDeprecatedTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTaskXmlReaderTest.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkConnectorDeprecated.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskDeprecated.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceConnectorDeprecated.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTaskDeprecated.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceConnectorDeprecatedTest.scala

Some of the options for byte storage will be replaced with an envelope method in future versions.  See #975 
This release branch will serve as a final release of this functionality before deprecated functionality (bytes write mode) is removed from the codebase.
The connectors will now be named
```
S3SinkTaskDeprecated
S3SourceTaskDeprecated
```
so that users will be aware they are using non-recommended/deprecated functionality.

RB-476 - Take a branch and rename the classes

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskTest.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/config/PartitionField.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/config/PartitionFieldSplitter.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/config/PartitionFieldSplitterTest.scala
kafka-connect-query-language/src/main/antlr4/ConnectorLexer.g4
kafka-connect-query-language/src/main/antlr4/ConnectorParser.g4
kafka-connect-query-language/src/test/java/com/datamountaineer/kcql/KcqlTest.scala

To distinguish between flattened and nested json structures in configuration
Currently a dot is a special character in the `KCQL PARTITIONBY` statements (connector dependent)
This currently works well for nested structures.  For example:
`
"myObject": {
"user": {
name: "Bob"
}
}
`
myObject.user.name will give us "Bob".
However it will not work for a flattened structure where the key contains a dot:
`
{ "myObject.user.name": "Bob" }
`
This PR ensures that you are able to specify in KCQL if the key should be respected whole by using backticks:
```
PARTITIONBY _key.`myObject.user.name`
```
where the part surrounded by backticks will be the section which must be used whole.
This fixes an issue reported via Lenses community Slack.

S3 Sink: Allow backticks in KCQL partition fields

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskAvroEnvelopeNullKeyOrValueTest.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/transformers/EnvelopeWithSchemaTransformer.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/transformers/EnvelopeWithSchemaTransformerTests.scala

An issue was present in the S3 sink handling null value. This was leading to an exception raised since the Connect struct for the envelope does not have the "value" field on null. The code change ensures the transformer does not populate the struct unless the filed is present.

Null values for sink

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3AvroWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3JsonWriterManagerTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/utils/ITSampleSchemaAndData.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/formats/writer/JsonFormatWriter.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/formats/writer/SinkData.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3WriterManager.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/ValueToSinkDataConverter.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/sink/extractors/SinkDataExtractor.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/formats/AvroFormatWriterTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/conversion/ValueToSinkDataConverterTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/utils/SampleData.scala

The PR introduces the support for S3 sink for BigDecimal.  A new case class extending SinkData is introduced. For text storage the safeValue function is overwritten to return the java BigDecimal. The JsonConverter is changed to store decimals as numbers, not base64 (default). While a breaking change, this should not be a cause of concern since BigDecimal was not handled before, so it should have created an error if that was the case.
Unit test and integration tests were added to ensure the storage can handle BigDecimal.

Support BigDecimal

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/cloud/common/sink/CoreSinkTaskTestCases.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/model/location/S3LocationValidator.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/config/S3SourceConfig.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/model/CloudLocationTest.scala
kafka-connect-azure-datalake/src/main/scala/io/lenses/streamreactor/connect/datalake/model/location/DatalakeLocationValidator.scala
kafka-connect-azure-datalake/src/test/scala/io/lenses/streamreactor/connect/datalake/model/location/DatalakeLocationValidatorTest.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/model/location/CloudLocation.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/model/location/CloudLocationValidator.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/config/CloudSinkBucketOptions.scala
kafka-connect-cloud-common/src/test/scala/io/lenses/streamreactor/connect/cloud/common/utils/SampleData.scala
kafka-connect-gcp-storage/src/it/scala/io/lenses/streamreactor/connect/cloud/common/sink/CoreSinkTaskTestCases.scala
kafka-connect-gcp-storage/src/main/scala/io/lenses/streamreactor/connect/gcp/storage/model/location/GCPStorageLocationValidator.scala
kafka-connect-gcp-storage/src/test/scala/io/lenses/streamreactor/connect/gcp/storage/model/location/GCPStorageLocationValidatorTest.scala

The cloud sinks (AWS S3, GCP Storage and Datalake) have a validation condition that prevents nested prefixes from being used.
This condition no longer seems to be needed and prevents more flexible behaviour, so in this PR, it has been removed.

Remove limiting condition

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceAvroWithValueAsArrayEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceAvroWithValueAsOptionalArrayEnvelopeTest.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/formats/reader/converters/SchemaAndValueEnvelopeConverter.scala

Storing the Key/Value as an array of bytes has an issue since the connector returns java.nio.ByteBuffer but the Connect framework ByteArrayConverter works only with byte[]
This change ensures that if the key/value are a ByteBuffer it converts that to byte[]

Byte Array Support

---

.gitignore
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTaskTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/storage/ListDirectoryTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/cloud/common/utils/AsyncIOAssertions.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTask.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/storage/AwsS3DirectoryLister.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/reader/S3PartitionDiscoveryTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/storage/AwsS3DirectoryListerTest.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/source/CloudSourceTask.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/source/distribution/CloudPartitionSearcher.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/source/distribution/PartitionSearcher.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/source/distribution/PartitionSearcherResponse.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/source/reader/PartitionDiscovery.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/storage/DirectoryLister.scala
kafka-connect-cloud-common/src/test/scala/io/lenses/streamreactor/connect/cloud/common/source/reader/PartitionDiscoveryTest.scala
kafka-connect-gcp-storage/src/main/scala/io/lenses/streamreactor/connect/gcp/storage/source/GCPStorageSourceConnector.scala
kafka-connect-gcp-storage/src/main/scala/io/lenses/streamreactor/connect/gcp/storage/source/GCPStorageSourceTask.scala
kafka-connect-gcp-storage/src/main/scala/io/lenses/streamreactor/connect/gcp/storage/storage/GCPStorageDirectoryLister.scala
kafka-connect-gcp-storage/src/test/scala/io/lenses/streamreactor/connect/gcp/storage/storage/GCPStorageDirectoryListerTest.scala

This introduces most of the functionality for the GCP Storage Source.
* Removes `DirectoryFindCompletionConfig` and `DirectoryFindResults` case classes as these were simple wrappers for primitive values and adding indirection to the code.
* Some functionality is pushed up from `S3SourceTask` into `CloudSourceTask` to be shared by all cloud connectors, with some abstract template methods defined in `CloudSourceTask` to ensure the functionality is implemented by all connectors.
* `S3PartitionSearcher` is promoted to cloud-commons module and renamed to `CloudPartitionSearcher`.
* `DirectoryLister` becomes a trait (interface) sitting in cloud-commons to be implemented by each source subproject.  Implementations of this trait are `GCPStorageDirectoryLister` and `AWSS3DirectoryLister`.
* …

Partition Search

---

kafka-connect-cassandra/src/main/scala/io/lenses/streamreactor/connect/cassandra/config/CassandraConfig.scala
kafka-connect-cassandra/src/main/scala/io/lenses/streamreactor/connect/cassandra/config/CassandraSettings.scala
kafka-connect-common/src/main/scala/io/lenses/streamreactor/common/config/base/traits/KcqlSettings.scala
kafka-connect-mongodb/src/main/scala/io/lenses/streamreactor/connect/mongodb/config/MongoSettings.scala
kafka-connect-redis/src/main/scala/io/lenses/streamreactor/connect/redis/sink/config/RedisConfig.scala
kafka-connect-redis/src/main/scala/io/lenses/streamreactor/connect/redis/sink/config/RedisSinkSettings.scala
kafka-connect-redis/src/main/scala/io/lenses/streamreactor/connect/redis/sink/rowkeys/RowKeyBuilderString.scala
kafka-connect-redis/src/main/scala/io/lenses/streamreactor/connect/redis/sink/rowkeys/StringStructFieldsStringKeyBuilder.scala
kafka-connect-redis/src/main/scala/io/lenses/streamreactor/connect/redis/sink/writer/RedisInsertSortedSet.scala
kafka-connect-redis/src/main/scala/io/lenses/streamreactor/connect/redis/sink/writer/RedisPubSub.scala
kafka-connect-redis/src/test/scala/io/lenses/streamreactor/connect/redis/sink/config/ConfigMultipleSortedSetsTest.scala
kafka-connect-redis/src/test/scala/io/lenses/streamreactor/connect/redis/sink/config/RedisSinkSettingsTest.scala
kafka-connect-redis/src/test/scala/io/lenses/streamreactor/connect/redis/sink/rowkeys/StringGenericRowKeyBuilderTest.scala
kafka-connect-redis/src/test/scala/io/lenses/streamreactor/connect/redis/sink/rowkeys/StringSinkRecordKeyBuilderTest.scala
kafka-connect-redis/src/test/scala/io/lenses/streamreactor/connect/redis/sink/rowkeys/StringStructFieldsStringKeyBuilderTest.scala

Remove some complexity from KcqlSettings where the functionality is only used for one connector (related classes only used once, and the related unit tests are also moved).

KCQLSettings Housekeeping

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceAvroEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceAvroWithValueAsArrayEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceAvroWithValueAsOptionalArrayEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceJsonEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceParquetEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceTaskXmlReaderTest.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/config/processors/kcql/DeprecationConfigDefProcessor.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/config/processors/DeprecationConfigDefProcessorTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/source/config/S3SourceConfigTest.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/source/config/CloudSourceSettingsKeys.scala

The following properties are described in the docs:
```
connect.s3.source.partition.search.continuous    
connect.s3.source.partition.search.interval      
connect.s3.source.partition.search.recurse.levels
```
And these follow the convention of the other properties.  However in implementation the properties are:
```
connect.s3.partition.search.continuous    
connect.s3.partition.search.interval      
connect.s3.partition.search.recurse.levels
```
This PR corrects the code to reflect the properties in the docs.  The `DeprecationConfigDefProcessor` will also cause an descriptive error on startup if the old property continues to be used, enabling the user to update their configuration to the correct one.
The error in the logs will look like this:
```
Change …
```

Fix discrepancy between code and docs for recurse levels/millis/mode

---

.github/workflows/release.yml

Fix for KCQL compilates that didn't get picked up for release in the first place because of github using `bash` (where `*` and `**` are treated the same by default, not like e.g. `zsh`)

fix for KCQL compilates to appear in the release (ambiguous BASH behaviour)

---

.github/workflows/release.yml

This commit adds antivirus checks via ClamAV on release builds.
The scan runs in two jobs, the first one refreshes the AV database and caches
it, then checks the repo itself for malicious files. Then the second job, runs
in a matrix and scans the build files including their dependencies.
We are being cautious and enable most of ClamAV's features.
Signed-off-by: Stefan Bocutiu <stefan.bocutiu@gmail.com>

[OPS-2283] CICD: Add AV checks before release

---

kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/naming/CloudKeyNamer.scala
kafka-connect-cloud-common/src/test/scala/io/lenses/streamreactor/connect/cloud/common/sink/naming/CloudKeyNamerTest.scala

At the moment an SMT can control the format of the key. For example it can set it to: yyyy-MM-dd/HH. But the connector replaces the `/` and thus breaks the key.
The change removes the code to replace the value and adds a test for it.

LC-187 Avoid adapting the partition fields value

---

.github/workflows/java-build.yml
.github/workflows/java-release.yml
.github/workflows/release.yml
java-connectors/.gitignore
java-connectors/build.gradle

Continuation of [this PR](https://github.com/lensesio/stream-reactor/pull/1145). Those changes to `Gradle` build and new scripts to GitHub Actions should allow `sbt` and `Gradle` builds to work simultaneously in order to allow for both java and scala connectors to be released alongside. This should also provide the base for further modules to be build by java and used by Scala.
Below testing was done:

GitHub actions for java connectors

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3JsonWriterManagerTest.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/conversion/ToJsonDataConverter.scala
suppression.xml

Some users have implemented SMTs that deviate from recommended best practices, returning Plain Old Java Objects (POJOs) instead of constructing Connect structs. Consequently, such SMTs encounter compatibility issues with the JsonConverter, which is designed to handle Connect data structures.
To address this, the proposed changes implement a mechanism to detect the presence of POJOs within the pipeline. Upon detection, the system leverages the Jackson Json writer to marshal the payload into JSON format, ensuring compatibility with the JsonConverter.
This code would only work for Json storage format and not for Avro/Parquet. We don't plan workarounds for those scenarios

LC-191 Workaround  Kafka Connect SMTs returning POJO

---

kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/naming/CloudKeyNamer.scala
kafka-connect-cloud-common/src/test/scala/io/lenses/streamreactor/connect/cloud/common/sink/naming/CloudKeyNamerTest.scala

* LC-187 Avoid adapting the partition fields value
At the moment an SMT can control the format of the key. For example, it can set it to: yyyy-MM-dd/HH. But the connector replaces the `/` and thus breaks the key.
The change removes the code to replace the value and adds a test for it.

LC-187 Avoid adapting the partition fields value (#1137)

---

java-connectors/kafka-connect-azure-eventhubs/src/test/java/io/lenses/streamreactor/connect/azure/eventhubs/source/EventHubsKafkaConsumerControllerTest.java

- **Method Extraction:** Extracted repetitive setup code into helper methods like mockKeyValueTypes, mockByteBlockingProducer, mockConsumerRecord, mockEmptyHeaders, and mockRecordsQueue.
- **Vararg Methods:** Made the mockRecordsQueue method varargs to accept variable numbers of input topics for better reusability.
- **Local Variable Removal:** Removed unnecessary local variables like emptyHeaderList and directly invoked Collections.emptyIterator() where needed.
- **Inline Initialization:** Initialized recordsQueue directly in the test methods instead of setting it up in setUp method, as it's only used within the scope of those methods.
- **Stream Processing:** Utilized Java Streams to simplify the creation of consumerRecordList in the mockRecordsQueue method.
- **Simplified Assertions:** …

Refactoring for simplicity

---

kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/config/kcqlprops/KeyNamerVersion.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/config/kcqlprops/PropsKeyEnum.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/config/kcqlprops/SinkPropsSchema.scala

Some customers are onboarding on 7.0 which will bring changes to the KCQL statement. For 8.0 there will be a new property to address faster seeks on the source.
By incorporating this property now, users can seamlessly integrate it into their workflows, preempting the need for a subsequent migration to the upcoming version 8.0.

LC-195: Introduce an 8.0 Compatibility Setting to Streamline Future Migrations

---

.github/workflows/build.yml

previous variable was only set for a PR, however the release uses a tag trigger.

Fix the release build

---

ADOPTERS.md

👋 
This PR adds an `ADOPTERS.md` file, along with an initial entry for Skillsoft, following the model from Strimzi & Kafka with _Powered By_.
The goal is that once created, it will encourage others that are currently using the connectors to update here, including existing Lenses.io customers + open-source users (e.g. CERN with MQTT).

Add `ADOPTERS.md`

---

kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/storage/AwsS3StorageFilter.scala
kafka-connect-aws-s3/src/main/scala/io/lenses/streamreactor/connect/aws/s3/storage/AwsS3StorageInterface.scala

The path of listing keys was missed. This meant that for scenarios where the S3 is read with a LastModified order, the change was not working.
It also removes the logging because it is extensive with every poll of the keys.

LC-200 Skip Glacier stored objects

---

build.sbt

Calls local gradlew file (if Gradle not installed)

Address gradlew issue when running sbt gradleSpotlessApply

---

kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/sink/S3SinkTaskAvroEnvelopeTest.scala
kafka-connect-aws-s3/src/it/scala/io/lenses/streamreactor/connect/aws/s3/source/S3SourceAvroEnvelopeTest.scala
kafka-connect-aws-s3/src/test/scala/io/lenses/streamreactor/connect/aws/s3/sink/config/S3SinkConfigDefBuilderTest.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/transformers/AddConnectSchemaTransformer.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/transformers/EnvelopeWithSchemaTransformer.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/transformers/SchemalessEnvelopeTransformer.scala
kafka-connect-cloud-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/sink/transformers/Transformers.scala
kafka-connect-common/src/main/scala/io/lenses/streamreactor/connect/cloud/common/model/TopicPartitionOffset.scala

To back the topics up the KCQL statemet is
```
INSERT INTO bucket
SELECT * FROM `*`
...
```
When `*` is used the envelope setting is ignored.
This change allows for the `*` to be taken into account as a default if the given message topic is not found.

LC-202 Backing up multiple topics at once

---

java-connectors/build.gradle

Fix to prefer latest git tag before build script version when building java connector JARs

fix to prefer tag before build script version for java JARs
